cluster_max_size: 1000
cluster_min_size: 50
cluster_tol: 0.02
plane_dist_thresh: 0.003
plane_max_iter: 50
ror_min_neighbors: 5
ror_radius_search: 0.01
voxel_leaf_size: 0.004
x_filter_max: 0.28
x_filter_min: -0.020000000000000018
y_filter_max: 0.09999999999999998
y_filter_min: -0.13
z_filter_max: 0.63
z_filter_min: 0.4
